config/routes.rb
Ecatalog::Application.routes.draw do
  resources :courses do
    collection do 
      post 'add'
    end
  end

  resources :students do
    collection do
      post 'add'
    end
  end

  resources :users
  resources :catalogs
  resources :login
  resources :sessions
  match 'clear' => 'login#clear'
  match 'logout' => 'sessions#destroy' 

  root :to => 'login#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecatalog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" >
        <a class="brand" href="#">
          eCatalog
        </a>
        <% if current_user %>
        <ul class="nav" />
          <li><%=link_to 'Acasa' , login_index_path %></li>
          <li><%=link_to 'Materii' , courses_path %></li>
          <li><%=link_to 'Elevi' , students_path %></li>
					<li><%=link_to 'Catalog' , catalogs_path %></li>
					<li><%=link_to 'Grafice' , '/catalogs/show' %></li>
        </ul>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" > <%= current_user.name %> </a>
          <ul class="dropdown-menu">
						<%= link_to 'Preferinte',edit_user_path(current_user) %>
            <a href="/logout">Iesire</a>
          </ul>
          </li>
        </ul>
      <%end%>
      </div>
    </div>
  </div>
    <div id="notificari",class="span3">
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= link_to 'x' , 'clear' ,remote: true%>
          <%=flash[:notice]%>
        </div>
      <%end%>
    </div>
  <div class="container">
  <%= yield %>
  </div>
</body>
</html>